name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    env:
      MOZ_HEADLESS: 1
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test
